name: Tests

on:
  push:
    paths:
      - '**/*.lua'
      - '.luacheckrc'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - '**/*.lua'
      - '.luacheckrc'
      - '.github/workflows/tests.yml'

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua

  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Luacheck
        uses: lunarmodules/luacheck@v1
        with:
          args: lua

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        nvim-versions: ['stable', 'nightly']
    name: test
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: run tests
        run: make test
